version: '3.8'

services:
  api:
    build: .
    command: python src/server.py --api-only
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  file-server:
    build: .
    command: python src/server.py --file-only
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - file-server
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://api:5000/api
      - VITE_FILE_SERVER_URL=http://file-server:5001/files